name: flutter_zitherharp
description: A shared library used for apps of Zither Harp.
version: 0.0.1
homepage: https://pub.dev/documentation/flutter_zitherharp
repository: https://github.com/zitherharpcommunity/flutter_zitherharp
issue_tracker: https://github.com/zitherharpcommunity/flutter_zitherharp/issues

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: any
  go_router: ^10.1.2
  share_plus: ^7.0.2
  flutter_bloc: ^8.1.4
  url_launcher: ^6.1.10
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.17
  
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  firebase_storage: ^11.6.0
  firebase_database: ^10.2.2
  firebase_app_check: ^0.2.1
  firebase_analytics: ^10.4.3
  firebase_crashlytics: ^3.3.2
  firebase_remote_config: ^4.2.3
  firebase_dynamic_links: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
