name: flutter_zitherharp
description: A shared library used for apps of Zither Harp.
version: 0.0.1
homepage: https://pub.dev/documentation/flutter_zitherharp
repository: https://github.com/zitherharpcommunity/flutter_zitherharp

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  go_router: ^10.1.2
  share_plus: ^7.0.2
  flutter_bloc: ^8.1.4
  url_launcher: ^6.1.10
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
